web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using core;
using core.Services;

namespace web.Controllers
{
	public abstract class BaseController : Controller
	{
		// services
		protected IUserAuthenticationService Authservice { get; set; }

		// cookies
		private string _authCookie = "SP-Auth";
		private string _userCookie = "SP-User";

        // constructor
        public BaseController(IUserAuthenticationService auth)
        {
            Authservice = auth;
        }

		// write cookies
		protected void WriteCookies(string setting, string settingValue, int expiry = 1)
		{
			// create server only cookie
			CookieOptions options = new CookieOptions()
			{
				Path = "/",
				HttpOnly = true,
				Secure = false,
				Expires = DateTime.Now.AddHours(expiry)
			};
			// write
			Response.Cookies.Append(setting, settingValue, options);
		}

		// read cookies
		protected string ReadCookies(string cookieName)
		{
			return Request.Cookies[cookieName];
		}

		// get authentication key
		public string GetAuthKey()
		{
			return ReadCookies(_authCookie);
		}

		// get user id
		public long GetCurrentUser()
		{
			return long.Parse(ReadCookies(_userCookie));
		}

		// set authentication key
		public void SetAuth(long userId, Guid key)
		{
			WriteCookies(_userCookie, userId.ToString());
			WriteCookies(_authCookie, key.ToString());
		}
		
		// set authentication key
		public void RemoveAuth()
		{
			WriteCookies(_userCookie, "", -1);
			WriteCookies(_authCookie, "", -1);
		}
		
		// check if user is authenticated
		public async Task<bool> CheckAccess()
		{
			// allow access for local development
			if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
			{
				return true;
			}
			
			// check if auth key is valid
			if (Guid.TryParse(GetAuthKey(), out Guid authkey))
			{
				return await Authservice.IsAuthenticated(authkey);
			}

			// if here no auth key
			return false;
		}

		// error respose
		public IActionResult ErrorResponse(string error)
		{
			return Json(new
			{
				code = 1,
				text = error
			});
		}
		// error respose
		public IActionResult SuccessResponse(string redirect = "")
		{
			return Json(new
			{
				code = 0,
				redirect = redirect
			});
		}

		// return no access error
		public IActionResult NoAccess()
		{
			return ErrorResponse("No Access");
		}
	}
}

web/Controllers/Web/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using core;
using core.Models;
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class AuthController : BaseController
    {
        public AuthController(IUserAuthenticationService auth) : base(auth)
        {
        }

		[HttpPost]
        public async Task<IActionResult> Login([FromBody]AuthModels.Login login)
        {
            // login 
            var res = await Authservice.Login(login.Username, login.Password);
            if (res.Success)
            {
                // set auth key for session
                SetAuth(res.UserId, res.AuthKey);

                // return to listing screen on login
                return SuccessResponse("/employee/listing");
            }

            // return error
            return ErrorResponse(res.Errors);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromBody]AuthModels.Register register)
        {
            // check passwords
            if (register.Password != register.ConfirmPassword)
            {
                return ErrorResponse("Passwords not matched.");
            }

            // define user
            var newuser = new core.Domain.User
            {
                Username = register.Username,
                Password = register.Password,
                FirstName = register.FirstName,
                LastName = register.LastName
            };

            // register user 
            var res = await Authservice.Register(newuser);
            if (res.Success)
            {
                return SuccessResponse("/");
            }
            // return error
            return ErrorResponse(res.Errors);
        }

        // logout
        public async Task<IActionResult> Logout()
        {
            if (await CheckAccess())
            {
                Authservice.Logout(GetCurrentUser());
            }
            
            // clear auth cookies
            RemoveAuth();
            
            return Redirect("/");
        }
    }
}

web/Controllers/Web/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using core;
using core.Models;
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers.Web
{
    public class EmployeeController : BaseController
    {
        private IEmployeePaymentService EmployeePaymentService { get; set; }
        private IListingService ListingService { get; }

        public EmployeeController(IUserAuthenticationService auth,
                                          IEmployeePaymentService empPayService,
                                          IListingService listingService) : base(auth)
        {
            EmployeePaymentService = empPayService;
            ListingService = listingService;
        }

        // employee listing screen
        public async Task<IActionResult> Listing()
        {
            // check auth
            if (!await CheckAccess())
            {
                return Redirect("/");
            }

            var emplList = await EmployeePaymentService.GetAllEmployees();
            var stateList = SeedingHelpers.StatesGenerator.List;
            var model = new core.Models.LisitngModels.ViewModel
            {
                EmplList = emplList.Select(x => new GenericModels.DropdownListItem
                {
                    Value = x.Id.ToString(),
                    Text = $"{x.FirstName} {x.LastName}"
                }),
                StatesList = stateList.Select(x => new GenericModels.DropdownListItem
                {
                    Value = x.Abbreviation,
                    Text = $"{x.Name}"
                })
            };
            return View(model);
        }
        
        // get employee listing results filtered
        [HttpPost]
        public async Task<IActionResult> GetListFiltered(LisitngModels.ListingRequest request)
        {
            // return filtered list
            return Ok(await ListingService.GetListFiltered(request));
        }
        
        // employee payments page
        [HttpGet("/[controller]/{empId}/[action]")]
        public async Task<IActionResult> Payments(long empId)
        {
            if (!await CheckAccess())
            {
                // show login screen if not authenticated
                return Redirect("/");
            }
            return View(empId);
        }

        // add employee partial
        public IActionResult AddEmployeeDialog()
        {
            return View("Partials/AddEmployee");
        }
        
        // record employee pay partial
        public IActionResult RecordPayDialog(long id)
        {
            return View("Partials/RecordPay", id);
        }
    }
}

web/Controllers/Web/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using core;
using core.Models;
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(IUserAuthenticationService auth) : base(auth)
        {
        }

        // login page
        public async Task<IActionResult> Index()
        {
            // go to employee listing screen if logged in already
            if (await CheckAccess())
            {
                return Redirect("/employee/listing");
            }

            // else show login page
            return View();
        }

        // error
        public IActionResult Error()
        {
            return View();
        }
    }
}

web/Views/Employee/Listing.cshtml
@model core.Models.LisitngModels.ViewModel
@{
    ViewData["Title"] = "Listing";
    ViewData["LoggedIn"] = true;
}

<h1>Employee Listing</h1>

<div ng-controller="ListingController" ng-init="init()">
	
	<a href="javascript:;;" class="btn btn-primary" ng-click="addNew()">Add New Employee</a>
    <div class="hidden">    
		<div class="search form-group" data-bootgrid-append="header">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Pay Date From" data-date-picker="" data-listing-filter="payPostingFrom" ng-model="model.payPostingFrom">
				<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
			</div>
		</div>
	    <div class="search form-group" data-bootgrid-append="header">
		    <div class="input-group">
			    <input type="text" class="form-control" placeholder="Pay Date End" data-date-picker="" data-listing-filter="payPostingTo" ng-model="model.payPostingTo">
			    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
		    </div>
	    </div>
		<div class="search form-group" data-bootgrid-append="header">
            <select class="form-control" data-listing-filter="empId" ng-model="model.empId">
                <option value="">Show All Employees</option>
                @foreach(var empl in Model.EmplList)
				{
                    <option value="@empl.Value">@empl.Text</option>
				}
            </select>
        </div>
		<div class="search form-group" data-bootgrid-append="header">
            <select class="form-control" data-listing-filter="state" ng-model="model.state">
                <option value="">Show All States</option>
                @foreach(var state in Model.StatesList)
                {
                    <option value="@state.Value">@state.Text</option>
                }
            </select>
        </div>
    </div>
	<table id="employee-listing" class="table table-condensed table-hover table-striped">
	    <thead>
	    <tr>
	        <th data-column-id="fullName" data-formatter="link">Employee</th>
	        <th data-column-id="state">State</th>
	        <th data-column-id="lastPaymentDate">Last Payment Date</th>
	        <th data-column-id="lastPaymentAmount" data-formatter="lpamount">Last Payment Amount</th>
	        <th data-column-id="ytdPay" data-formatter="ytdpay">YTD Pay</th>
	    </tr>
	    </thead>
	</table>
</div>

web/Views/Employee/Payments.cshtml
@using core
@model long
@{
    ViewBag.Title = "Employee";
    ViewData["LoggedIn"] = true;
    var empId = Model;
	var statesList = DropdownListHelpers.GetStatesList();
}

<div ng-controller="EmpPaymentsController" ng-init="init(@empId)" ng-cloak>
	<h2>Employee: {{model.employee.firstName}} {{model.employee.lastName}}</h2>
	<div class="row">
		<div class="col-sm-12">
			<form name="frm">
				<div class="panel panel-primary">
					<div class="panel-heading">Employee Details
						<a href="javascript:;;" class="btn btn-xs btn-success" ng-if="frm.$dirty" ng-click="saveEmp()">Save Changes</a>
						<span style="color: #ff0400">{{status.validationErrors}}</span>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-4">
								<div class="form-group required">
									<label for="FirstName" class="control-label">First Name</label>
									<input type="text" class="form-control" id="FirstName" ng-model="model.employee.firstName" min="0" required>
								</div>                     
							</div>
							<div class="col-sm-4">
								<div class="form-group required">
									<label for="LastName" class="control-label">Last Name</label>
									<input type="text" class="form-control" id="LastName" ng-model="model.employee.lastName" min="0" required>
								</div>                     
							</div>
							<div class="col-sm-4">
								<div class="form-group required">
									<label class="control-label">State</label>
									<select class="form-control" ng-model="model.employee.state" required>
										@foreach (var state in statesList)
										{
											<option value="@state.Value">@state.Text</option>
										}
									</select>
								</div>   
							</div>
						</div>
						
						<div class="row">
							<div class="col-sm-4">
								<div class="form-group">
									<label>SSN</label>
									<div class="field-readonly">{{model.employee.ssn | ssnFormat:true}}</div>
								</div>
							</div>
							<div class="col-sm-4">
								<div class="form-group required">
									<label for="Insurance" class="control-label">Insurance</label>
									<input type="number" class="form-control" id="Insurance" ng-model="model.employee.insurance" min="0" required>
								</div>
							</div>
							<div class="col-sm-4">
								<div class="form-group required">
									<label for="W4Allowances"  class="control-label">W4 Allowances</label>
									<input type="number" class="form-control" id="W4Allowances" ng-model="model.employee.w4Allowances" min="0" required>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-sm-4">
								<div class="form-group required">
									<label for="Retirement401KPercent" class="control-label">401k %</label>
									<input type="number" class="form-control" id="Retirement401KPercent" ng-model="model.employee.retirement401KPercent" min="0" required>
								</div>
							</div>
							<div class="col-sm-4">
								<div class="checkbox">
									<label><input type="checkbox" id="Retirement401kPreTax" ng-model="model.employee.retirement401KPreTax">401k Pre Tax</label>
								</div>
							</div>
						</div>
						
					</div>
				</div>
			</form>

			<div class="panel panel-primary">
				<div class="panel-heading">Pay History</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-6 text-left">
							<a href="javascript:;;" class="btn btn-primary" ng-click="recordPay()">Record Pay</a>
							YTD Gross: <span class="label label-primary">{{model.ytdGross | currency}}</span>
							YTD Net: <span class="label label-primary">{{model.ytdNet | currency}}</span>
						</div>
						<div class="col-sm-6 text-right">
							<div class="btn-group" role="group" aria-label="Basic example">
								<button type="button" class="btn btn-default" ng-click="refreshPayements(model.currentPage - 1)" ng-disabled="model.currentPage == 1"><span class="glyphicon glyphicon-menu-left"></span>Prev</button>
								<button type="button" class="btn btn-default">{{model.currentPage}}</button>
								<button type="button" class="btn btn-default" ng-click="refreshPayements(model.currentPage +  1)" ng-disabled="model.payments.length < 10">Next<span class="glyphicon glyphicon-menu-right"></span></button>
							</div>
						</div>
					</div>
					<div class="table-responsive">
						<table class="table table-striped">
							<thead>
							<tr>
								<th class="text-center">Pay Date</th>
								<th class="text-center">Payment Period</th>
								<th class="text-center">Gross Pay</th>
								<th class="text-center">Fed Tax</th>
								<th class="text-center">State Tax</th>
								<th class="text-center">SSN Tax</th>
								<th class="text-center">Medicare</th>
								<th class="text-center">Insurance</th>
								<th class="text-center">401K</th>
								<th class="text-center">Net Pay</th>
							</tr>
							</thead>
							<tbody>
							<tr ng-repeat="pay in model.payments">
								<td class="text-center">{{pay.createDateTime | date:"MM/dd/yyyy"}}</td>
								<td class="text-center">{{pay.paymentPeriodFrom | date:"MM/dd/yyyy"}} to {{pay.paymentPeriodTo | date:"MM/dd/yyyy"}}</td>
								<td class="text-center">{{pay.grossPay | currency}}</td>
								<td class="text-center">{{pay.fedTax | currency}}</td>
								<td class="text-center">{{pay.stateTax | currency}}</td>
								<td class="text-center">{{pay.socialSecurityTax | currency}}</td>
								<td class="text-center">{{pay.medicareTax | currency}}</td>
								<td class="text-center">{{pay.insurance | currency}}</td>
								<td class="text-center">{{pay.retirement401K | currency}}</td>
								<td class="text-center">{{pay.netPay | currency}}</td>
							</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Login";
    ViewData["LoggedIn"] = false;
}

<h1>Welcome to Simple Payroll!</h1>
<div ng-controller="LoginController" class="well ng-cloak" ng-cloak>
    <h2 ng-if="!status.Register">Login </h2>
    <h2 ng-if="status.Register">Register</h2>
    <span class="text-danger" ng-bind="status.ValidatationErrors"></span>
    <span class="text-success" ng-bind="status.Instructions"></span>
    <div class="row">
        <div class="col-sm-4">
            <form name="frm">
                <div ng-if="!status.Register">
                    <div class="form-group">
                      <label for="Username">User Name:</label>
                      <input type="text" class="form-control" id="Username" ng-model="model.Username" required>
                    </div>
                    <div class="form-group">
                      <label for="pwd">Password:</label>
                      <input type="password" class="form-control" id="pwd" ng-model="model.Password" required>
                    </div>      
                    <a href="javascript:;;" type="button" class="btn btn-primary" ng-click="login()">Login</a>
                    <a href="javascript:;;" type="button" class="btn btn-link" ng-click="switchScreen(true)">Register</a>
                </div>      

                <div ng-if="status.Register">
                    <div class="form-group required">
                      <label for="Username" class="control-label">User Name:</label>
                      <input type="text" class="form-control" id="Username" ng-model="model.Username" required>
                    </div>
                    <div class="form-group required">
                      <label for="FirstName" class="control-label">First Name:</label>
                      <input type="text" class="form-control" id="FirstName" ng-model="model.FirstName" required>
                    </div>
                    <div class="form-group required">
                      <label for="LastName" class="control-label">Last Name:</label>
                      <input type="text" class="form-control" id="LastName" ng-model="model.LastName" required>
                    </div>
                    <div class="form-group required">
                      <label for="pwd" class="control-label">Password:</label>
                      <input type="password" class="form-control" id="pwd" ng-model="model.Password" required>
                    </div>
                    <div class="form-group required" ng-if="status.Register">
                      <label for="cpwd" class="control-label">Confirm Password:</label>
                      <input type="password" class="form-control" id="cpwd" ng-model="model.ConfirmPassword" required>
                    </div>
                    <a href="javascript:;;" type="button" class="btn btn-primary" ng-click="register()">Register</a>
                    <a href="javascript:;;" type="button" class="btn btn-link" ng-click="switchScreen(false)">Login</a>
                </div>
            </form>
        </div>
    </div>
</div>

web/Views/Shared/Partials/AddEmployee.cshtml
@using core;
@using core.Models;
﻿﻿@{
    Layout = null;
	var statesList = SeedingHelpers.StatesGenerator.List
	                .Select(x => new GenericModels.DropdownListItem
	                {
	                    Value = x.Abbreviation,
	                    Text = $"{x.Name}"
	                });
}
<div ng-controller="AddEmployeeController">
	<div class="row">
        <div class="col-sm-12">
			<form name="frm">
				<div class="row">
					<div class="col-sm-4">
						<div class="form-group required">
		                  <label for="FirstName" class="control-label">First Name</label>
		                  <input type="text" class="form-control" id="FirstName" ng-model="model.firstName" required>
		                </div>
					</div>
					<div class="col-sm-4">
						<div class="form-group required">
		                  <label for="LastName" class="control-label">Last Name</label>
		                  <input type="text" class="form-control" id="LastName" ng-model="model.lastName" required>
		                </div>
					</div>
					<div class="col-sm-4">
                        <div class="form-group required">
                          <label for="State" class="control-label">State</label>
	                        <select class="form-control" id="State" ng-model="model.state" required>
	                            @foreach(var state in statesList)
	                            {
	                                <option value="@state.Value">@state.Text</option>
	                            }
	                        </select>
                        </div>
					</div>               
				</div>
				<div class="row">
					<div class="col-sm-4">
						<div class="form-group required">
                        	<label for="SSN" class="control-label">SSN</label>
							<input type="text" class="form-control" id="SSN" ng-model="model.ssn" ssn placeholder="###-##-####" required>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-group required">
                        	<label for="Insurance" class="control-label">Insurance</label>
							<input type="number" class="form-control" id="Insurance" ng-model="model.insurance" min="0" required>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-group required">
                        	<label for="W4Allowances" class="control-label">W4 Allowances</label>
							<input type="number" class="form-control" id="W4Allowances" ng-model="model.w4Allowances" min="0" required>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<div class="form-group required">
                        	<label for="Retirement401KPercent" class="control-label">401k %</label>
							<input type="number" class="form-control" id="Retirement401KPercent" ng-model="model.retirement401KPercent" min="0" required>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="checkbox">
                        	<label><input type="checkbox" id="Retirement401kPreTax" ng-model="model.retirement401KPreTax">401k Pre Tax</label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-6 col-sm-offset-6 text-right">
						<span class="text-danger" ng-bind="status.validationErrors"></span>
						<a href="javascript:;;" class="btn btn-link" ng-click="cancel()">Cancel</a>						
						<a href="javascript:;;" class="btn btn-primary" ng-click="add()">Add Employee</a>
					</div>
				</div>
		    </form>
		</div>
	</div>
</div>

web/Views/Shared/Partials/RecordPay.cshtml
@model long
@{
    Layout = null;
    var empId = Model;
}
<div ng-controller="RecordPayController">
    <form name="frm">
        <div class="hidden" ng-bind="model.empId" ng-init="model.empId=@empId"></div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group required">
                    <label for="GrossPay" class="control-label">Salary</label>
                    <input type="number" class="form-control" id="GrossPay" ng-model="model.grossPay" ng-change="getAllDeductions()" min="0" required>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group required">
                    <label for="PaymentPeriodFrom" class="control-label">Pay Period Start Date</label>
                    <div class="input-group">
                        <input type="text" class="form-control" data-date-picker id="PaymentPeriodFrom" ng-model="model.paymentPeriodFrom" required>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group required">
                    <label for="PaymentPeriodTo" class="control-label">Pay Period End Date</label>
                    <div class="input-group">
                        <input type="text" data-date-picker class="form-control" id="PaymentPeriodTo" ng-model="model.paymentPeriodTo" required>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Insurance">Insurance</label>
                    <div class="field-readonly" id="Insurance">{{model.insurance | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="W4Alloances">W4 Allowances</label>
                    <div class="field-readonly" id="W4Alloances">{{model.w4Allowances | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Retirement401K">401K</label>
                    <div class="field-readonly" id="Retirement401K">{{model.retirement401K | currency}}</div>
                </div>
            </div>
        </div>
        
        <div class="row">
            
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="TaxableIncome">Taxable Income</label>
                    <div class="field-readonly" id="TaxableIncome">{{model.taxableIncome | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="FedTax">Fed Tax</label>
                    <div class="field-readonly" id="FedTax">{{model.fedTax | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="StateTax">StateTax</label>
                    <div class="field-readonly" id="StateTax">{{model.stateTax | currency}}</div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="SocialSecurityTax">Social Security Tax</label>
                    <div class="field-readonly" id="SocialSecurityTax">{{model.socialSecurityTax | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="MedicareTax">Medicare Tax</label>
                    <div class="field-readonly" id="MedicareTax">{{model.medicareTax | currency}}</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="NetPay">Net Pay</label>
                    <div class="field-readonly" id="NetPay">{{model.netPay | currency}}</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-sm-offset-6 text-right">
                <span class="text-danger" ng-bind="status.validationErrors"></span>
                <a href="javascript:;;" class="btn btn-link" ng-click="cancel()">Cancel</a>						
                <a href="javascript:;;" class="btn btn-primary" ng-click="pay()">Pay</a>
            </div>
        </div>
    </form>
</div>

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simple Payroll</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootgrid/jquery.bootgrid.min.css" />
    <link rel="stylesheet" href="~/lib/date-picker/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body ng-app="app">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Simple Payroll</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
				@{
                    if((bool)ViewData["LoggedIn"])
	                {
	                    <li><a asp-area="" asp-controller="Auth" asp-action="Logout">Logout&nbsp;<i class="glyphicon glyphicon-log-out"></i></a></li>
	                }
			    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Simple Payroll</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootbox/bootbox.min.js"></script>
    <script src="~/lib/bootgrid/jquery.bootgrid.min.js"></script>
    <script src="~/lib/bootgrid/jquery.bootgrid.fa.min.js"></script>
    <script src="~/lib/date-picker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/angular.js"></script>
    <script src="~/js/forms.js"></script>
    <script src="~/js/filters/ssn.js"></script>
    <script src="~/js/directives/ssn.js"></script>
    <script src="~/js/controllers/login-controller.js"></script>
    <script src="~/js/controllers/listing-controller.js"></script>
    <script src="~/js/controllers/add-employee-controller.js"></script>
    <script src="~/js/controllers/emp-payments-controller.js"></script>
    <script src="~/js/controllers/record-pay-controller.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>